---
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Purfakt/config-repo
          #uri: http://odyssey.devoteam.be/netflix-team/config-repo
          #username: sdethuin
          #password:
          search-paths:
            - 'api*'
http:
  sslverify: false
